# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.box_check_update = true
    config.vm.provider "virtualbox" do |v|
        v.name = "docker1"
        v.memory = 8192
        v.cpus = 4
    end
end

Vagrant.configure("2") do |config|
    for i in 8000..9000
        config.vm.network "forwarded_port", guest: i, host: i
    end
    #config.vm.synced_folder ".", "/vagrant", {:mount_options => ['dmode=777','fmode=777']}
end

